"""Freeze Qwen H0 on exactly the Gemini half-Testing timeline; no paid requests or GT."""
import argparse
from collections import Counter
from copy import deepcopy
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT), str(ROOT/'src')]
from scripts import run_testing_half_pipeline as core

SOURCE = ROOT/'artifacts/data/h0_baselines/surgical_h0_baseline_grok_qwen_20260910'
OUTPUT = ROOT/'artifacts/evaluation/qwen38_testing_half_probe_20260916'
MODEL = 'qwen3.8-max'


def prepare(output):
    parent, timeline = core.scope_rows(core.SCOPE)
    metadata = {}
    bound = {}
    for folder in sorted(SOURCE.glob('qwen38_h0_jpeg_testing_*')):
        manifest = core.read(folder/'manifest.json')
        if manifest['model'] != MODEL or manifest['split'] != 'testing':
            raise ValueError('unexpected Qwen delivery identity')
        for path in (folder/'manifest.json', folder/'requests.json'):
            bound[str(path.relative_to(ROOT))] = core.sha(path)
        for r in core.read(folder/'requests.json'):
            identity = folder.name, r['custom_id']
            if identity in metadata:
                raise ValueError('duplicate delivered request')
            metadata[identity] = r
    wanted = {s['key'] for s in timeline}
    index = {}
    folder = SOURCE/'qwen38_h0_batch_collected_v3/records'
    for n, path in enumerate(sorted(folder.glob('*.json')), 1):
        # Filenames retain the custom ID; only selected timestamps need opening.
        parts = path.stem.split('_')
        if len(parts) < 3 or '_'.join(parts[-2:]) not in wanted:
            continue
        raw = path.read_bytes()
        r = json.loads(raw)
        request = metadata[(r['artifact'], r['custom_id'])]
        key = request['video_id']+'_'+str(request['target_frame_id'])
        if key in index:
            raise ValueError('duplicate Qwen result; resolve explicitly: '+key)
        if r['status'] != 'SCHEMA_VALID':
            continue
        if r['returned_model'] != MODEL:
            raise ValueError('Qwen response model changed')
        labels = core.app.frozen.gated.h0_from_raw(r['prediction'])
        core.tracker_pipeline.original.make_pool(labels)
        index[key] = dict(key=key, video_id=request['video_id'], frame_id=request['target_frame_id'],
            causal_frame_ids=request['causal_frame_ids'], record_path=str(path.resolve()),
            record_sha256=core.hashlib.sha256(raw).hexdigest(), h0=labels, model=MODEL,
            prepared_dir=str((SOURCE/r['artifact']).resolve()), custom_id=r['custom_id'])
        if n % 1000 == 0:
            print('Checked Qwen records: '+str(n), flush=True)
    selected, counts = [], Counter()
    for original in timeline:
        s = {k:deepcopy(original[k]) for k in ('key','video_id','frame_id','stage','evaluation_target',
                                               'causal_frame_ids','decoder_indices_zero_based')}
        h0 = index.get(s['key'])
        reuse = h0 is not None and h0['causal_frame_ids'] == s['causal_frame_ids']
        s['h0_action'] = 'reuse_exact_three_frame_h0' if reuse else 'generate_qwen_h0'
        if reuse:
            s.update(cached_record_path=h0['record_path'], cached_record_sha256=h0['record_sha256'],
                     prepared_dir=h0['prepared_dir'], custom_id=h0['custom_id'])
        counts[s['h0_action']] += 1
        selected.append(s)
    output.mkdir(parents=True, exist_ok=False)
    for name, data in [('h0_index.jsonl',list(index.values())), ('frame_inventory.jsonl',selected)]:
        with (output/name).open('x', encoding='utf-8') as stream:
            for row in data:
                stream.write(json.dumps(row, ensure_ascii=False)+'\n')
    spec = deepcopy(parent)
    spec.update(base_model=MODEL, status='QWEN_HALF_SCOPE_FROZEN',
        h0_index=str((output/'h0_index.jsonl').resolve().relative_to(ROOT)),
        parent_scope_path=str(core.SCOPE), parent_scope_sha256=core.sha(core.SCOPE/'run_scope.json'),
        new_or_rebuilt_h0=counts['generate_qwen_h0'], reusable_exact_h0=counts['reuse_exact_three_frame_h0'],
        frame_inventory_sha256=core.sha(output/'frame_inventory.jsonl'),
        source_sha256={**bound, str((output/'h0_index.jsonl').resolve().relative_to(ROOT)):core.sha(output/'h0_index.jsonl')},
        data_provenance={'inputs':'Qwen H0 only; missing/short-context rows regenerated by Qwen',
                         'comparison':'same Gemini half timeline and evaluation keys',
                         'proposal_model':'google/gemini-3.8-flash', 'reviewers':'unchanged',
                         'gate':'fixed Gemini-trained 54-feature Gate; cross-backbone transfer evaluation'})
    for video in spec['videos']:
        group = [s for s in selected if s['video_id'] == video['video_id']]
        video['counts'] = dict(Counter(s['stage']+':'+s['h0_action'] for s in group))
        video['counts'].update(pipeline=sum(s['stage']=='pipeline' for s in group),
                               evaluation_targets=sum(s['evaluation_target'] for s in group),
                               warmup_h0_only=sum(s['stage']=='warmup_h0_only' for s in group))
    core.write(output/'run_scope.json',spec)
    core.write(output/'suggested_budget_limits.json',{'openrouter_usd':'120','aliyun_cny':'200',
               'glm_requests':'8578','deepseek_requests':'8578','xai_usd':'0'})
    print(json.dumps({'scope':str(output), 'base_model':MODEL,'counts':counts,
                      'pipeline':8578,'scored':7823,'api_calls':0}),flush=True)


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--output',type=Path,default=OUTPUT)
    prepare(p.parse_args().output.resolve())
